# https://kubernetes.io/docs/concepts/services-networking/ingress/
# https://github.com/kubernetes/ingress/tree/master/controllers/nginx
# https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md

---

apiVersion: v1
kind: Secret
#type: kubernetes.io/tls
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQwRENDQXJpZ0F3SUJBZ0lKQUloZ3lCd1pzcnBLTUEwR0NTcUdTSWIzRFFFQkN3VUFNR0V4Q3pBSkJnTlYKQkFZVEFrSlNNUmN3RlFZRFZRUUlEQTVUWVc1MFlTQkRZWFJoY21sdVlURVJNQThHQTFVRUJ3d0lVMkZ2SUVwdgpjMlV4RFRBTEJnTlZCQXNNQkVsR1UwTXhGekFWQmdOVkJBTU1Ebk5xTG1sbWMyTXVaV1IxTG1KeU1CNFhEVEUzCk1EWXhOakU1TVRjeU1sb1hEVEkzTURZeE5ERTVNVGN5TWxvd1lURUxNQWtHQTFVRUJoTUNRbEl4RnpBVkJnTlYKQkFnTURsTmhiblJoSUVOaGRHRnlhVzVoTVJFd0R3WURWUVFIREFoVFlXOGdTbTl6WlRFTk1Bc0dBMVVFQ3d3RQpTVVpUUXpFWE1CVUdBMVVFQXd3T2Myb3VhV1p6WXk1bFpIVXVZbkl3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUURGbDh3RzhLODVBZ1k0bGRGQ1c3WjFZOUFMR2VGemw1UGtwUkpsZ0doZVZwRUsKcmJ5Q0hlV0tMZktyUCswSVVGU1RHYVFCaUp2SSt1MCtDOHpIMmQzdm1tZnhJYWd4ejdIZUw5a083dzJGeTdTTwowTS9YTXhxRXNDL0J4ZVBDai83WW42TnZ5bHR3YmFaclNENzcwVHF0NHBjeU5Xb0hYQVo5bmxJdGVUVUtSM0VyCjdNbkZ5L2lCeDZRR0VhK2tLNUFyY01ZN3BQZlZUSjV1ZGNlSDA4SDlFV3JPeU9Ba1AzL0pOME5SNjNyVGNJU0sKQU1IR1lVaFpJREQ0NC84bXhYMGc5VkRNSko2UnNiYWxCc2UwcU15Zm9PNm5uQ2RUN3p5ekdLRkE0MnJKaWRQcwpFaG9wTncwSDVzRmFBWTRsSWRnc3RmNWpWQUwxR0RDWEd4bHRITFlUQWdNQkFBR2pnWW93Z1ljd0NRWURWUjBUCkJBSXdBREFMQmdOVkhROEVCQU1DQmVBd2JRWURWUjBSQkdZd1pJSVNkM2QzTG5OcUxtbG1jMk11WldSMUxtSnkKZ2hWdVpYUmliM2d1YzJvdWFXWnpZeTVsWkhVdVluS0NHWEp2WTJ0bGRHTm9ZWFF1YzJvdWFXWnpZeTVsWkhVdQpZbktIQkw4a0NBU0hCTDhrQ0FXSEJMOGtDQWFIQkw4a0NBZUhCTDhrQ0Fnd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSlVCV1ZRY3FvSDFkdHNiUUozcXFUUFQ5LzVURmM0SERzbVZ2TzJxd283WEZ4NUdsT3JINXpUbDE3T0QKNnJyVy9EeW1KVHBwU0ZNcndyeThuRU1zbzE1VzhTWWIwaXJYb1Nveks2Rk5sZUl1blpDMGptQlFnSTJIbmltTwpNQ1p2TnhkemdKVkZDak9heE9PYUpSK0ZZM1Q4ckkyWG1DbUp1N0Y3MFhxK2luTUR6bjJYdjVudlEzcUZ5dXBvCnVoazB1ZklTQUxrZmFEcUFuNjFVS3hrS2ZiUDQzZUVNTC8wakxqWFU0MUlUU3hqekhFNzNGc085dFpXR3BESWUKaVl6OHdmazQvMWlTcGJ6M0crYUZNWGlYNU5Xd1Q0bCtJWm5yY1ZhbmplRXZ2OWVXUGx6cDh6Rjc4MjNubDl5QgpQaUdraUlKOStHOTFXNDZVSlRUakg5TDlNU0k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBeFpmTUJ2Q3ZPUUlHT0pYUlFsdTJkV1BRQ3huaGM1ZVQ1S1VTWllCb1hsYVJDcTI4CmdoM2xpaTN5cXovdENGQlVreG1rQVlpYnlQcnRQZ3ZNeDluZDc1cG44U0dvTWMreDNpL1pEdThOaGN1MGp0RFAKMXpNYWhMQXZ3Y1hqd28vKzJKK2piOHBiY0cybWEwZysrOUU2cmVLWE1qVnFCMXdHZlo1U0xYazFDa2R4Syt6Sgp4Y3Y0Z2Nla0JoR3ZwQ3VRSzNER082VDMxVXllYm5YSGg5UEIvUkZxenNqZ0pEOS95VGREVWV0NjAzQ0VpZ0RCCnhtRklXU0F3K09QL0pzVjlJUFZRekNTZWtiRzJwUWJIdEtqTW42RHVwNXduVSs4OHN4aWhRT05xeVluVDdCSWEKS1RjTkIrYkJXZ0dPSlNIWUxMWCtZMVFDOVJnd2x4c1piUnkyRXdJREFRQUJBb0lCQUYybC9UQUk0TE0vTDEyZwpQQWFjV3hTMkVzTkFKK2RXSHVVT0MzTUo4ZTFNVC8va3FlUnRjUDRWbXQ3cE5GbHRZVGc2dmMxd1JvMXh5QUZSCkxHUkg4UFQvbEdYbmtzVFE4RGNqTEZmMG1zOGY1ZHFPUXdOMm1BbnRTeVVtdWpUYmRHaU0rTFFpRDBadzRhQVYKSkt6SzFHblhhOXVERDFhZm1mL3RpbnM4NkJPUFJVbUtWTmpXd09xMHQvbitHdnNMUFNGamVyR1U2RUxPN1cvWgphM2lyNnUzenlmOW8zbmFSQkxxMGZxOUE5cUVVdERZL0dJMFo3eDM0V2hSS2tsU2l3ZFZMajFsTHJ0OUh1ZmVJCmJaRU1PeUdoSjZLaThmUFkyWVkvajZUckxydjlUakQ5Q1NmV3VaQ2ZIS2RJdFRuWGo5c3hDSjExZFJEMlR1NmsKcmg2NVkxa0NnWUVBNmlpVTkvT2FFQkVOdjhSZlZUQmY4SVhLZnlpNHIxdUlKdWhBN0JIQndtWGxQQm5BZ0ZmNAozVVhLd084anZkajdXRjRZazdadFI0aVZrcFF1K3dLUWJGbnhnMm0xUUczVFBiRStOQzBWeEN0QWR3WTdBR242Cm5BN3ZxTy9GZU5HeU15TmtYSXJSM1JyZkR0MDdjV1d0Ylc5bkU5MjF2NkZ6TzBPM2hwcklkMGNDZ1lFQTJBWVQKQVZlWHNFU3pnYjZFenlHRDV0R0lSdEZqR1U5V1BRaWdhMEdHZTlSRmp6dnBZSzg2U1QxdXFFQS84azEvODFIVgpXVmF3WEV6R2RFRjU0RFNNMWx2WHh2dFdadHc3OVN2WFhwenVQbnNtTmpWVkZNSkJtRlVwUnB4R211WmNhMUVOCi9PQTlpRWlzZjdqOFgxWmpzbHo0WU5pWXRqOWlBSjRTVDVUT3lOVUNnWUFjTGZ3WGh2S0FnbnprR2k3YTRySjUKRUxEWThyNmZJK1hUd05tblQwL0JKR0FkQm9CYk1ic2FiZjdEajBQKzRmRUZwblZRdVlDWFBrRzUzU2wyUGMzQgpyR1ZiU2twczBZcTlmdW9jZjF5Q09pNU01S3dQRmJINk8vWHRuOFZsRDk5aE5oNHE0TzMyclBneElzQzNtZVB3CktwcitFZzJBWFY2dndDdURBSGVsbXdLQmdBNDYwRE90Ym11SkN2NEg2NzJ0S29BZzIwWTI4cjB2RWJJeGlFZW8KYUZCdDJpc21PaWhKUXFDaWNGQ2E4dHRtS1lDQXFub1pFTUx6dDdyZXVVV0FrS3BxSUZ1V0lNbmp4ZnRQYVA5dApmUEFXc3B5dGhLNDZZWkhFUWxUSlpJazlsV2JvVHZDU1lOdENWa0tQaitoRHk0dHJQbDA2eDB4eC9tV21BL1RFCkM1OEZBb0dBZDljM3gzcWg1M0N4K3FKeHNJbWE3Z0dTMEY0MjFkL2NUOHE1VFQwcEtUQW5YSCtvbUpnQ08wb2QKZG1ZVDl6NlhoV3RUd2VjZ3YyazFsZ3hIQWF6ZnhWcitWSXhSVTRybm5UL3NMUGVkWVZkQ3lSeGluYmloV3luUgpRVHQ0Wk1yV1JyOFhQbmFVeGVwM3gxeXluSmNzeGZUME9SajRlNS8wb2ZkSUQxajBnc2s9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
metadata:
  name: ingress-nginx

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-protocols: "TLSv1.2"
    ingress.kubernetes.io/ssl-ciphers: "HIGH:!aNULL:!MD5"
spec:
  tls:
  - secretName: ingress-nginx
  rules:
  - host: netbox.sj.ifsc.ed.br
    http:
      paths:
      - path: /
        backend:
          serviceName: netbox
          servicePort: 80
  - host: rocketchat.sj.ifsc.edu.br
    http:
      paths:
      - path: /
        backend:
          serviceName: rocketchat
          servicePort: 3000
